{{- if .Values.application.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name }}
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/dom-lc/lc-k8s-apps.git
      targetRevision: {{ .Values.application.branchName }}
      path: charts/{{ .Values.application.name }}
      helm:
        valueFiles:
          - {{ .Values.application.helm.valuesFile }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}