{{- if .Values.applicationset.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.applicationset.name }}
  namespace: argocd
spec:
  generators:
    - list:
          elements:
          {{- range .Values.applicationset.generators.list.elements }}
            - name: {{ .name }}
              version: {{ .version }}
          {{- end }}
  template:
    metadata:
      name: '{{`{{name}}`}}'
      namespace: '{{`{{name}}`}}'
    spec:
      project: default
      sources:
        - repoURL: {{ .Values.applicationset.sources.chartRepo.repoUrl }}
          targetRevision: '{{`{{version}}`}}'
          path: 'charts/{{`{{name}}`}}'
          helm:
            valueFiles:
              - $values/{{`{{name}}`}}/{{ $.Values.applicationset.sources.valuesRepo.valuesFile }}
        - repoURL: {{ .Values.applicationset.sources.valuesRepo.repoUrl }}
          targetRevision: {{ .Values.applicationset.sources.valuesRepo.targetRevision }}
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{name}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        {{- range .Values.applicationset.syncOptions }}
          - {{ . }}
        {{- end }}
      ignoreDifferences:
      {{- range .Values.applicationset.ignoreDifferences }}
        - group: {{ .group | quote }}
          kind: {{ .kind | quote }}
          {{- if .namespace }}
          namespace: {{ .namespace | quote }}
          {{- end }}
          {{- if .jsonPointers }}
          jsonPointers:
          {{- range .jsonPointers }}
            - {{ . | quote }}
          {{- end }}
          {{- end }}
          {{- if .jqPathExpressions }}
          jqPathExpressions:
          {{- range .jqPathExpressions }}
            - {{ . | quote }}
          {{- end }}
          {{- end }}
      {{- end}}
{{- end }}