{{- if .Values.applicationset.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-apps
  namespace: argocd
spec:
  generators:
    - list:
          elements:
          {{- range .Values.applicationset.generators.list.elements }}
            - name: {{ .name }}
              version: {{ .version }}
          {{- end }}
  template:
    metadata:
      name: '{{`{{name}}`}}'
      namespace: '{{`{{name}}`}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/dom-lc/lc-k8s-apps-deployments.git
          targetRevision: '{{`{{version}}`}}'
          path: 'charts/{{`{{name}}`}}'
          helm:
            valueFiles:
              - $values/{{`{{name}}`}}/{{ $.Values.applicationset.sources.valuesRepo.valuesFile }}
        - repoURL: https://github.com/dom-lc/lc-k8s-apps-values.git
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{name}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      ignoreDifferences:
      - group: "apps"
        kind: "Secret"
        jsonPointers:
          - "/data"
      - group: "external-secrets.io"
        kind: "ExternalSecret"
        namespace: "actions-runner-system"
        jqPathExpressions:
          - ".spec.data[].remoteRef.conversionStrategy"
          - ".spec.data[].remoteRef.decodingStrategy"
          - ".spec.data[].remoteRef.metadataPolicy"
{{- end }}