name: Merge New App

on:
  workflow_dispatch: {}

jobs:
  new-app:
    runs-on: surveillance-hosted-k8s-apps-deployments
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v4
      
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Get application name
        id: get-app-name
        run: |
          APP_NAME=$(yq '.application.name' ./clusters/surveillance-green/new-app.application.yaml)
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
      # Remove the new app test application created in test Phase
      - name: Delete ArgoCD Test Application
        run: |
          kubectl delete application "$APP_NAME" -n argocd

      # Remove the new app test application created in test Phase
      - name: Remove the test application
        run: |
          kubectl destroy application -n argocd