applicationset:
  enabled: true
  name: k8s-apps
  chartRepo: https://github.com/dom-lc/lc-k8s-apps.git
  generators:
    # The List generator allows you to target Argo CD Applications to clusters based on a fixed list of any chosen key/value element pairs.
    # We will be using the list to choose the targetRevion for each application
    list:
      # Please make sure all applications under your directories are included 
      # specially if you are using expressions like *
      elements:
        - name: argocd
          version: argocd-v0.1.0
        - name: cert-manager
          version: cert-manager-v0.1.0
        - name: reflector
          version: reflector-v0.1.0
        - name: actions-runner-system
          version: actions-runner-system-v0.2.0
        - name: external-secrets
          version: external-secrets-v0.1.0
  # This is the list of Helm value files to use for the application
  # Note that these files are relative to the root of the Git repository
  # and should be present in the directories specified above
  sources:
    chartRepo: 
      repoUrl: https://github.com/dom-lc/lc-k8s-apps.git
    valuesRepo:
      # Repository containing your your Helm Values files
      repoUrl: https://github.com/dom-lc/lc-k8s-apps-values.git
      targetRevision: HEAD
      # Name of values file
      valuesFile: values-surveillance-green.yaml
  # Sync options for the application
  # Note that these options are used for the sync policy of the application
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  ignoreDifferences:
    # This is the list of fields to ignore for the application
    # Note that these fields are used for the ignore differences policy of the application
    - group: apps
      kind: Secret
      jsonPointers:
        - /data
    - group: external-secrets.io
      kind: ExternalSecret
      namespace: actions-runner-system
      jqPathExpressions:
        - '.spec.data[].remoteRef.conversionStrategy'
        - '.spec.data[].remoteRef.decodingStrategy'
        - '.spec.data[].remoteRef.metadataPolicy'
