# This file is used to define the values for the Argo CD ApplicationSet
# It is used in conjoncture with the app-management Chart to create an ApplicationSet
# This file defines values for the surveillance-green cluster.
applicationset:
  enabled: true
  generators:
    # The List generator allows you to target Argo CD Applications to clusters based on a fixed list of any chosen key/value element pairs.
    # We will be using the list to choose the targetRevion for each application
    list:
      # Please make sure all applications under your directories are included 
      # specially if you are using expressions like *
      elements:
        - name: argocd
          version: argocd-v0.1.0
        - name: cert-manager
          version: cert-manager-v0.1.0
        - name: reflector
          version: reflector-v0.1.0
        - name: actions-runner-system
          version: actions-runner-system-v0.1.0
        - name: external-secrets
          version: external-secrets-v0.1.0
        - name: py-show-vars
          version: py-show-vars-v0.1.0
  # This is the list of Helm value files to use for the application
  # Note that these files are relative to the root of the Git repository
  # and should be present in the directories specified above
  sources:
      # Name of values file
      valuesFile: values-surveillance-green.yaml
